apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-page
  labels:
    app: static-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-page
  template:
    metadata:
      labels:
        app: static-page
